:- discontiguous dir/2.
:- discontiguous direct_nested/2.
:- discontiguous pkg/1.
:- discontiguous imports/2.
nested(X, Y) :- direct_nested(X, Y), dir(X, _), dir(Y, _).
nested(X, Y) :- direct_nested(Z, Y), nested(X, Z).
pkg_dir(X) :- dir(X), pkg(X).
dependency(X, Y) :- imports(X, Y), pkg(X), pkg(Y).
dependency(X, Y) :- imports(Z, Y), dependency(X, Z).
p_label(M, D, Y) :- mark(M, Y), dir(Y, D).
p_label(M, D, Y) :- mark(M, Z), nested(Z, Y), dir(Z, D).
d_label(M, Y) :- p_label(M, D, Y), p_label(M2, D2, Y), M \== M2, D2 > D.
label(M, Y) :- p_label(M, _, Y), \+ d_label(M, Y).
violation(X, Y) :- dependency(X, Y), label(M, X), label(M2, Y), M \== M2, M < M2.
broken(X, Y) :- violation(X, Y), \+ exception(X, Y).
pkg("github.com/blevesearch/bleve/search").
imports("github.com/blevesearch/bleve/search","github.com/blevesearch/bleve/index").
imports("github.com/blevesearch/bleve/search","github.com/blevesearch/bleve/document").
imports("github.com/blevesearch/bleve/search","github.com/blevesearch/bleve/numeric").
dir("github.com",0).
dir("github.com/blevesearch",1).
direct_nested("github.com","github.com/blevesearch").
dir("github.com/blevesearch/bleve",2).
direct_nested("github.com/blevesearch","github.com/blevesearch/bleve").
dir("github.com/blevesearch/bleve/search",3).
direct_nested("github.com/blevesearch/bleve","github.com/blevesearch/bleve/search").
pkg("github.com/blevesearch/bleve/search/highlight/fragmenter/simple").
imports("github.com/blevesearch/bleve/search/highlight/fragmenter/simple","github.com/blevesearch/bleve/registry").
imports("github.com/blevesearch/bleve/search/highlight/fragmenter/simple","github.com/blevesearch/bleve/search/highlight").
dir("github.com/blevesearch/bleve/search/highlight",4).
direct_nested("github.com/blevesearch/bleve/search","github.com/blevesearch/bleve/search/highlight").
dir("github.com/blevesearch/bleve/search/highlight/fragmenter",5).
direct_nested("github.com/blevesearch/bleve/search/highlight","github.com/blevesearch/bleve/search/highlight/fragmenter").
dir("github.com/blevesearch/bleve/search/highlight/fragmenter/simple",6).
direct_nested("github.com/blevesearch/bleve/search/highlight/fragmenter","github.com/blevesearch/bleve/search/highlight/fragmenter/simple").
pkg("github.com/blevesearch/bleve").
imports("github.com/blevesearch/bleve","github.com/blevesearch/bleve/index").
imports("github.com/blevesearch/bleve","github.com/blevesearch/bleve/index/store/gtreap").
imports("github.com/blevesearch/bleve","github.com/blevesearch/bleve/index/upsidedown").
imports("github.com/blevesearch/bleve","github.com/blevesearch/bleve/registry").
imports("github.com/blevesearch/bleve","github.com/blevesearch/bleve/search/highlight/highlighter/html").
imports("github.com/blevesearch/bleve","github.com/blevesearch/bleve/index/store/boltdb").
imports("github.com/blevesearch/bleve","github.com/blevesearch/bleve/document").
imports("github.com/blevesearch/bleve","github.com/blevesearch/bleve/index/store").
imports("github.com/blevesearch/bleve","github.com/blevesearch/bleve/mapping").
imports("github.com/blevesearch/bleve","github.com/blevesearch/bleve/search").
imports("github.com/blevesearch/bleve","github.com/blevesearch/bleve/search/collector").
imports("github.com/blevesearch/bleve","github.com/blevesearch/bleve/search/facet").
imports("github.com/blevesearch/bleve","github.com/blevesearch/bleve/search/highlight").
imports("github.com/blevesearch/bleve","github.com/blevesearch/bleve/search/query").
imports("github.com/blevesearch/bleve","github.com/blevesearch/bleve/analysis").
imports("github.com/blevesearch/bleve","github.com/blevesearch/bleve/search/highlight/highlighter/ansi").
imports("github.com/blevesearch/bleve","github.com/blevesearch/bleve/numeric").
imports("github.com/blevesearch/bleve","github.com/blevesearch/bleve/analysis/analyzer/keyword").
imports("github.com/blevesearch/bleve","github.com/blevesearch/bleve/index/store/null").
pkg("github.com/blevesearch/bleve/document").
imports("github.com/blevesearch/bleve/document","github.com/blevesearch/bleve/analysis").
imports("github.com/blevesearch/bleve/document","github.com/blevesearch/bleve/numeric").
dir("github.com/blevesearch/bleve/document",3).
direct_nested("github.com/blevesearch/bleve","github.com/blevesearch/bleve/document").
pkg("github.com/blevesearch/bleve/analysis").
dir("github.com/blevesearch/bleve/analysis",3).
direct_nested("github.com/blevesearch/bleve","github.com/blevesearch/bleve/analysis").
pkg("github.com/steveyen/gtreap").
dir("github.com/steveyen",1).
direct_nested("github.com","github.com/steveyen").
dir("github.com/steveyen/gtreap",2).
direct_nested("github.com/steveyen","github.com/steveyen/gtreap").
pkg("github.com/blevesearch/bleve/registry").
imports("github.com/blevesearch/bleve/registry","github.com/blevesearch/bleve/analysis").
imports("github.com/blevesearch/bleve/registry","github.com/blevesearch/bleve/search/highlight").
imports("github.com/blevesearch/bleve/registry","github.com/blevesearch/bleve/index").
imports("github.com/blevesearch/bleve/registry","github.com/blevesearch/bleve/index/store").
dir("github.com/blevesearch/bleve/registry",3).
direct_nested("github.com/blevesearch/bleve","github.com/blevesearch/bleve/registry").
pkg("github.com/blevesearch/bleve/search/highlight").
imports("github.com/blevesearch/bleve/search/highlight","github.com/blevesearch/bleve/document").
imports("github.com/blevesearch/bleve/search/highlight","github.com/blevesearch/bleve/search").
pkg("github.com/blevesearch/bleve/index/store/boltdb").
imports("github.com/blevesearch/bleve/index/store/boltdb","github.com/boltdb/bolt").
imports("github.com/blevesearch/bleve/index/store/boltdb","github.com/blevesearch/bleve/index/store").
imports("github.com/blevesearch/bleve/index/store/boltdb","github.com/blevesearch/bleve/registry").
dir("github.com/blevesearch/bleve/index",3).
direct_nested("github.com/blevesearch/bleve","github.com/blevesearch/bleve/index").
dir("github.com/blevesearch/bleve/index/store",4).
direct_nested("github.com/blevesearch/bleve/index","github.com/blevesearch/bleve/index/store").
dir("github.com/blevesearch/bleve/index/store/boltdb",5).
direct_nested("github.com/blevesearch/bleve/index/store","github.com/blevesearch/bleve/index/store/boltdb").
pkg("github.com/blevesearch/go-porterstemmer").
dir("github.com/blevesearch/go-porterstemmer",2).
direct_nested("github.com/blevesearch","github.com/blevesearch/go-porterstemmer").
pkg("github.com/blevesearch/bleve/numeric").
dir("github.com/blevesearch/bleve/numeric",3).
direct_nested("github.com/blevesearch/bleve","github.com/blevesearch/bleve/numeric").
pkg("github.com/blevesearch/bleve/search/highlight/format/html").
imports("github.com/blevesearch/bleve/search/highlight/format/html","github.com/blevesearch/bleve/registry").
imports("github.com/blevesearch/bleve/search/highlight/format/html","github.com/blevesearch/bleve/search/highlight").
dir("github.com/blevesearch/bleve/search/highlight/format",5).
direct_nested("github.com/blevesearch/bleve/search/highlight","github.com/blevesearch/bleve/search/highlight/format").
dir("github.com/blevesearch/bleve/search/highlight/format/html",6).
direct_nested("github.com/blevesearch/bleve/search/highlight/format","github.com/blevesearch/bleve/search/highlight/format/html").
pkg("github.com/blevesearch/bleve/mapping").
imports("github.com/blevesearch/bleve/mapping","github.com/blevesearch/bleve/registry").
imports("github.com/blevesearch/bleve/mapping","github.com/blevesearch/bleve/analysis").
imports("github.com/blevesearch/bleve/mapping","github.com/blevesearch/bleve/document").
imports("github.com/blevesearch/bleve/mapping","github.com/blevesearch/bleve/analysis/analyzer/standard").
imports("github.com/blevesearch/bleve/mapping","github.com/blevesearch/bleve/analysis/datetime/optional").
dir("github.com/blevesearch/bleve/mapping",3).
direct_nested("github.com/blevesearch/bleve","github.com/blevesearch/bleve/mapping").
pkg("github.com/blevesearch/bleve/search/facet").
imports("github.com/blevesearch/bleve/search/facet","github.com/blevesearch/bleve/index").
imports("github.com/blevesearch/bleve/search/facet","github.com/blevesearch/bleve/numeric").
imports("github.com/blevesearch/bleve/search/facet","github.com/blevesearch/bleve/search").
dir("github.com/blevesearch/bleve/search/facet",4).
direct_nested("github.com/blevesearch/bleve/search","github.com/blevesearch/bleve/search/facet").
pkg("github.com/blevesearch/bleve/search/highlight/format/ansi").
imports("github.com/blevesearch/bleve/search/highlight/format/ansi","github.com/blevesearch/bleve/registry").
imports("github.com/blevesearch/bleve/search/highlight/format/ansi","github.com/blevesearch/bleve/search/highlight").
dir("github.com/blevesearch/bleve/search/highlight/format/ansi",6).
direct_nested("github.com/blevesearch/bleve/search/highlight/format","github.com/blevesearch/bleve/search/highlight/format/ansi").
pkg("github.com/blevesearch/segment").
dir("github.com/blevesearch/segment",2).
direct_nested("github.com/blevesearch","github.com/blevesearch/segment").
pkg("github.com/blevesearch/bleve/analysis/token/stop").
imports("github.com/blevesearch/bleve/analysis/token/stop","github.com/blevesearch/bleve/analysis").
imports("github.com/blevesearch/bleve/analysis/token/stop","github.com/blevesearch/bleve/registry").
dir("github.com/blevesearch/bleve/analysis/token",4).
direct_nested("github.com/blevesearch/bleve/analysis","github.com/blevesearch/bleve/analysis/token").
dir("github.com/blevesearch/bleve/analysis/token/stop",5).
direct_nested("github.com/blevesearch/bleve/analysis/token","github.com/blevesearch/bleve/analysis/token/stop").
pkg("github.com/blevesearch/bleve/analysis/analyzer/keyword").
imports("github.com/blevesearch/bleve/analysis/analyzer/keyword","github.com/blevesearch/bleve/analysis").
imports("github.com/blevesearch/bleve/analysis/analyzer/keyword","github.com/blevesearch/bleve/analysis/tokenizer/single").
imports("github.com/blevesearch/bleve/analysis/analyzer/keyword","github.com/blevesearch/bleve/registry").
dir("github.com/blevesearch/bleve/analysis/analyzer",4).
direct_nested("github.com/blevesearch/bleve/analysis","github.com/blevesearch/bleve/analysis/analyzer").
dir("github.com/blevesearch/bleve/analysis/analyzer/keyword",5).
direct_nested("github.com/blevesearch/bleve/analysis/analyzer","github.com/blevesearch/bleve/analysis/analyzer/keyword").
pkg("github.com/blevesearch/bleve/analysis/token/porter").
imports("github.com/blevesearch/bleve/analysis/token/porter","github.com/blevesearch/bleve/analysis").
imports("github.com/blevesearch/bleve/analysis/token/porter","github.com/blevesearch/bleve/registry").
imports("github.com/blevesearch/bleve/analysis/token/porter","github.com/blevesearch/go-porterstemmer").
dir("github.com/blevesearch/bleve/analysis/token/porter",5).
direct_nested("github.com/blevesearch/bleve/analysis/token","github.com/blevesearch/bleve/analysis/token/porter").
pkg("github.com/blevesearch/bleve/analysis/tokenizer/unicode").
imports("github.com/blevesearch/bleve/analysis/tokenizer/unicode","github.com/blevesearch/segment").
imports("github.com/blevesearch/bleve/analysis/tokenizer/unicode","github.com/blevesearch/bleve/analysis").
imports("github.com/blevesearch/bleve/analysis/tokenizer/unicode","github.com/blevesearch/bleve/registry").
dir("github.com/blevesearch/bleve/analysis/tokenizer",4).
direct_nested("github.com/blevesearch/bleve/analysis","github.com/blevesearch/bleve/analysis/tokenizer").
dir("github.com/blevesearch/bleve/analysis/tokenizer/unicode",5).
direct_nested("github.com/blevesearch/bleve/analysis/tokenizer","github.com/blevesearch/bleve/analysis/tokenizer/unicode").
pkg("github.com/blevesearch/bleve/analysis/tokenizer/single").
imports("github.com/blevesearch/bleve/analysis/tokenizer/single","github.com/blevesearch/bleve/analysis").
imports("github.com/blevesearch/bleve/analysis/tokenizer/single","github.com/blevesearch/bleve/registry").
dir("github.com/blevesearch/bleve/analysis/tokenizer/single",5).
direct_nested("github.com/blevesearch/bleve/analysis/tokenizer","github.com/blevesearch/bleve/analysis/tokenizer/single").
pkg("github.com/blevesearch/bleve/index").
imports("github.com/blevesearch/bleve/index","github.com/blevesearch/bleve/document").
imports("github.com/blevesearch/bleve/index","github.com/blevesearch/bleve/index/store").
pkg("github.com/blevesearch/bleve/index/store/gtreap").
imports("github.com/blevesearch/bleve/index/store/gtreap","github.com/steveyen/gtreap").
imports("github.com/blevesearch/bleve/index/store/gtreap","github.com/blevesearch/bleve/index/store").
imports("github.com/blevesearch/bleve/index/store/gtreap","github.com/blevesearch/bleve/registry").
dir("github.com/blevesearch/bleve/index/store/gtreap",5).
direct_nested("github.com/blevesearch/bleve/index/store","github.com/blevesearch/bleve/index/store/gtreap").
pkg("github.com/blevesearch/bleve/search/highlight/highlighter/simple").
imports("github.com/blevesearch/bleve/search/highlight/highlighter/simple","github.com/blevesearch/bleve/search").
imports("github.com/blevesearch/bleve/search/highlight/highlighter/simple","github.com/blevesearch/bleve/search/highlight").
imports("github.com/blevesearch/bleve/search/highlight/highlighter/simple","github.com/blevesearch/bleve/document").
imports("github.com/blevesearch/bleve/search/highlight/highlighter/simple","github.com/blevesearch/bleve/registry").
dir("github.com/blevesearch/bleve/search/highlight/highlighter",5).
direct_nested("github.com/blevesearch/bleve/search/highlight","github.com/blevesearch/bleve/search/highlight/highlighter").
dir("github.com/blevesearch/bleve/search/highlight/highlighter/simple",6).
direct_nested("github.com/blevesearch/bleve/search/highlight/highlighter","github.com/blevesearch/bleve/search/highlight/highlighter/simple").
pkg("github.com/blevesearch/bleve/analysis/token/lowercase").
imports("github.com/blevesearch/bleve/analysis/token/lowercase","github.com/blevesearch/bleve/analysis").
imports("github.com/blevesearch/bleve/analysis/token/lowercase","github.com/blevesearch/bleve/registry").
dir("github.com/blevesearch/bleve/analysis/token/lowercase",5).
direct_nested("github.com/blevesearch/bleve/analysis/token","github.com/blevesearch/bleve/analysis/token/lowercase").
pkg("github.com/blevesearch/bleve/search/highlight/highlighter/ansi").
imports("github.com/blevesearch/bleve/search/highlight/highlighter/ansi","github.com/blevesearch/bleve/registry").
imports("github.com/blevesearch/bleve/search/highlight/highlighter/ansi","github.com/blevesearch/bleve/search/highlight").
imports("github.com/blevesearch/bleve/search/highlight/highlighter/ansi","github.com/blevesearch/bleve/search/highlight/format/ansi").
imports("github.com/blevesearch/bleve/search/highlight/highlighter/ansi","github.com/blevesearch/bleve/search/highlight/fragmenter/simple").
imports("github.com/blevesearch/bleve/search/highlight/highlighter/ansi","github.com/blevesearch/bleve/search/highlight/highlighter/simple").
dir("github.com/blevesearch/bleve/search/highlight/highlighter/ansi",6).
direct_nested("github.com/blevesearch/bleve/search/highlight/highlighter","github.com/blevesearch/bleve/search/highlight/highlighter/ansi").
pkg("github.com/boltdb/bolt").
dir("github.com/boltdb",1).
direct_nested("github.com","github.com/boltdb").
dir("github.com/boltdb/bolt",2).
direct_nested("github.com/boltdb","github.com/boltdb/bolt").
pkg("github.com/blevesearch/bleve/analysis/lang/en").
imports("github.com/blevesearch/bleve/analysis/lang/en","github.com/blevesearch/bleve/analysis").
imports("github.com/blevesearch/bleve/analysis/lang/en","github.com/blevesearch/bleve/registry").
imports("github.com/blevesearch/bleve/analysis/lang/en","github.com/blevesearch/bleve/analysis/token/lowercase").
imports("github.com/blevesearch/bleve/analysis/lang/en","github.com/blevesearch/bleve/analysis/token/porter").
imports("github.com/blevesearch/bleve/analysis/lang/en","github.com/blevesearch/bleve/analysis/tokenizer/unicode").
imports("github.com/blevesearch/bleve/analysis/lang/en","github.com/blevesearch/bleve/analysis/token/stop").
dir("github.com/blevesearch/bleve/analysis/lang",4).
direct_nested("github.com/blevesearch/bleve/analysis","github.com/blevesearch/bleve/analysis/lang").
dir("github.com/blevesearch/bleve/analysis/lang/en",5).
direct_nested("github.com/blevesearch/bleve/analysis/lang","github.com/blevesearch/bleve/analysis/lang/en").
pkg("github.com/blevesearch/bleve/search/searcher").
imports("github.com/blevesearch/bleve/search/searcher","github.com/blevesearch/bleve/search").
imports("github.com/blevesearch/bleve/search/searcher","github.com/blevesearch/bleve/index").
imports("github.com/blevesearch/bleve/search/searcher","github.com/blevesearch/bleve/search/scorer").
imports("github.com/blevesearch/bleve/search/searcher","github.com/blevesearch/bleve/numeric").
dir("github.com/blevesearch/bleve/search/searcher",4).
direct_nested("github.com/blevesearch/bleve/search","github.com/blevesearch/bleve/search/searcher").
pkg("github.com/blevesearch/bleve/search/scorer").
imports("github.com/blevesearch/bleve/search/scorer","github.com/blevesearch/bleve/search").
imports("github.com/blevesearch/bleve/search/scorer","github.com/blevesearch/bleve/index").
dir("github.com/blevesearch/bleve/search/scorer",4).
direct_nested("github.com/blevesearch/bleve/search","github.com/blevesearch/bleve/search/scorer").
pkg("github.com/blevesearch/bleve/analysis/analyzer/standard").
imports("github.com/blevesearch/bleve/analysis/analyzer/standard","github.com/blevesearch/bleve/analysis").
imports("github.com/blevesearch/bleve/analysis/analyzer/standard","github.com/blevesearch/bleve/analysis/lang/en").
imports("github.com/blevesearch/bleve/analysis/analyzer/standard","github.com/blevesearch/bleve/analysis/token/lowercase").
imports("github.com/blevesearch/bleve/analysis/analyzer/standard","github.com/blevesearch/bleve/analysis/tokenizer/unicode").
imports("github.com/blevesearch/bleve/analysis/analyzer/standard","github.com/blevesearch/bleve/registry").
dir("github.com/blevesearch/bleve/analysis/analyzer/standard",5).
direct_nested("github.com/blevesearch/bleve/analysis/analyzer","github.com/blevesearch/bleve/analysis/analyzer/standard").
pkg("github.com/blevesearch/bleve/search/collector").
imports("github.com/blevesearch/bleve/search/collector","github.com/blevesearch/bleve/search").
imports("github.com/blevesearch/bleve/search/collector","github.com/blevesearch/bleve/index").
dir("github.com/blevesearch/bleve/search/collector",4).
direct_nested("github.com/blevesearch/bleve/search","github.com/blevesearch/bleve/search/collector").
pkg("github.com/blevesearch/bleve/index/store/null").
imports("github.com/blevesearch/bleve/index/store/null","github.com/blevesearch/bleve/index/store").
imports("github.com/blevesearch/bleve/index/store/null","github.com/blevesearch/bleve/registry").
dir("github.com/blevesearch/bleve/index/store/null",5).
direct_nested("github.com/blevesearch/bleve/index/store","github.com/blevesearch/bleve/index/store/null").
pkg("github.com/blevesearch/bleve/index/store").
pkg("github.com/blevesearch/bleve/index/upsidedown").
imports("github.com/blevesearch/bleve/index/upsidedown","github.com/blevesearch/bleve/analysis").
imports("github.com/blevesearch/bleve/index/upsidedown","github.com/blevesearch/bleve/document").
imports("github.com/blevesearch/bleve/index/upsidedown","github.com/blevesearch/bleve/index").
imports("github.com/blevesearch/bleve/index/upsidedown","github.com/blevesearch/bleve/index/store").
imports("github.com/blevesearch/bleve/index/upsidedown","github.com/blevesearch/bleve/registry").
dir("github.com/blevesearch/bleve/index/upsidedown",4).
direct_nested("github.com/blevesearch/bleve/index","github.com/blevesearch/bleve/index/upsidedown").
pkg("github.com/blevesearch/bleve/search/highlight/highlighter/html").
imports("github.com/blevesearch/bleve/search/highlight/highlighter/html","github.com/blevesearch/bleve/registry").
imports("github.com/blevesearch/bleve/search/highlight/highlighter/html","github.com/blevesearch/bleve/search/highlight").
imports("github.com/blevesearch/bleve/search/highlight/highlighter/html","github.com/blevesearch/bleve/search/highlight/format/html").
imports("github.com/blevesearch/bleve/search/highlight/highlighter/html","github.com/blevesearch/bleve/search/highlight/fragmenter/simple").
imports("github.com/blevesearch/bleve/search/highlight/highlighter/html","github.com/blevesearch/bleve/search/highlight/highlighter/simple").
dir("github.com/blevesearch/bleve/search/highlight/highlighter/html",6).
direct_nested("github.com/blevesearch/bleve/search/highlight/highlighter","github.com/blevesearch/bleve/search/highlight/highlighter/html").
pkg("github.com/blevesearch/bleve/analysis/datetime/optional").
imports("github.com/blevesearch/bleve/analysis/datetime/optional","github.com/blevesearch/bleve/analysis").
imports("github.com/blevesearch/bleve/analysis/datetime/optional","github.com/blevesearch/bleve/analysis/datetime/flexible").
imports("github.com/blevesearch/bleve/analysis/datetime/optional","github.com/blevesearch/bleve/registry").
dir("github.com/blevesearch/bleve/analysis/datetime",4).
direct_nested("github.com/blevesearch/bleve/analysis","github.com/blevesearch/bleve/analysis/datetime").
dir("github.com/blevesearch/bleve/analysis/datetime/optional",5).
direct_nested("github.com/blevesearch/bleve/analysis/datetime","github.com/blevesearch/bleve/analysis/datetime/optional").
pkg("github.com/blevesearch/bleve/analysis/datetime/flexible").
imports("github.com/blevesearch/bleve/analysis/datetime/flexible","github.com/blevesearch/bleve/analysis").
imports("github.com/blevesearch/bleve/analysis/datetime/flexible","github.com/blevesearch/bleve/registry").
dir("github.com/blevesearch/bleve/analysis/datetime/flexible",5).
direct_nested("github.com/blevesearch/bleve/analysis/datetime","github.com/blevesearch/bleve/analysis/datetime/flexible").
pkg("github.com/blevesearch/bleve/search/query").
imports("github.com/blevesearch/bleve/search/query","github.com/blevesearch/bleve/index").
imports("github.com/blevesearch/bleve/search/query","github.com/blevesearch/bleve/mapping").
imports("github.com/blevesearch/bleve/search/query","github.com/blevesearch/bleve/search").
imports("github.com/blevesearch/bleve/search/query","github.com/blevesearch/bleve/search/searcher").
imports("github.com/blevesearch/bleve/search/query","github.com/blevesearch/bleve/analysis/datetime/optional").
imports("github.com/blevesearch/bleve/search/query","github.com/blevesearch/bleve/numeric").
imports("github.com/blevesearch/bleve/search/query","github.com/blevesearch/bleve/registry").
imports("github.com/blevesearch/bleve/search/query","github.com/blevesearch/bleve/analysis").
dir("github.com/blevesearch/bleve/search/query",4).
direct_nested("github.com/blevesearch/bleve/search","github.com/blevesearch/bleve/search/query").
